server:
  port: 8088

spring:
  application:
    name: yyrpc-demo-consumer

yyrpc:
  zkServer: localhost:2181
  zkRoot: yyrpc

app:
  id: app1
  namespace: public
  env: dev
  retries: 2
  timeout: 1000
  grayRatio: 33
  faultLimit: 10 # 30s 内10次错误则隔离
  halfOpenInitialDelay: 10000
  halfOpenDelay: 60000

logging:
  level:
    root: info
    cn.youyou.yyrpc: debug