
server:
  port: 8081

yyrpc:
  zk:
    server: localhost:2181
    root: yyrpc
  app:
    id: app1
    namespace: public
    env: dev
  provider:
    metas:
      dc: bj
      gray: false
      unit: B001
      tc: 0

logging:
  level:
    root: info
    cn.youyou.yyrpc: debug